import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.drlizlondon.peopleos',
  appName: 'PeopleOS',
  // Generated by `npm run build:native`; never edit ios/App/App/public by hand.
  webDir: 'dist-native',
  plugins: {
    LocalNotifications: {
      presentationOptions: ['sound', 'banner', 'list']
    }
  }
};

export default config;
